name: Dynamic Databricks Notebook Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install tools
      run: sudo apt-get install -y jq curl

    - name: Export Notebooks from Source Workspace
      run: |
        ORIGIN_HOST=${{ secrets.DATABRICKS_ORIGIN_HOST }}
        ORIGIN_TOKEN=${{ secrets.DATABRICKS_ORIGIN_TOKEN }}
        NOTEBOOK_BASE_PATH="/Workspace/Users/instructor_datasmartada@outlook.com/source"
        NOTEBOOKS=("mount_adls_storage" "mount_adls_storage_v1")  # Agrega aquí más notebooks si necesitas

        mkdir -p notebooks_to_deploy

        for nb in "${NOTEBOOKS[@]}"; do
          echo "Exportando $nb..."
          curl -s -X GET \
            -H "Authorization: Bearer $ORIGIN_TOKEN" \
            "$ORIGIN_HOST/api/2.0/workspace/export?path=$NOTEBOOK_BASE_PATH/$nb&format=SOURCE" \
            --output notebooks_to_deploy/$nb.py
        done

    - name: Deploy all notebooks to Destination Workspace
      run: |
        DEST_HOST=${{ secrets.DATABRICKS_DEST_HOST }}
        DEST_TOKEN=${{ secrets.DATABRICKS_DEST_TOKEN }}
        DEST_BASE_PATH="/py"

        for file in notebooks_to_deploy/*.py; do
          filename=$(basename "$file" .py)
          dest_folder="$DEST_BASE_PATH"  # Puedes ajustar esto si quieres subcarpetas
          dest_path="$dest_folder/$filename"

          echo "Creando carpeta de destino si no existe: $dest_folder"
          curl -s -X POST \
            -H "Authorization: Bearer $DEST_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"path\": \"$dest_folder\"}" \
            "$DEST_HOST/api/2.0/workspace/mkdirs"

          echo "Importando notebook: $file → $dest_path"
          curl -s -X POST \
            -H "Authorization: Bearer $DEST_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "path=$dest_path" \
            -F "format=SOURCE" \
            -F "language=PYTHON" \
            -F "overwrite=true" \
            -F "content=@$file" \
            "$DEST_HOST/api/2.0/workspace/import"
        done

    - name: Clean up
      run: rm -rf notebooks_to_deploy

    - name: Done
      run: echo "All notebooks deployed successfully!"
